apiVersion: k3d.io/v1alpha2
kind: Simple
name: k3d-demo
servers: 3
agents: 2
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443" # Kubernetes API via localhost:6443
image: rancher/k3s:v1.19.4-k3s1
volumes:
  - volume: /tmp:/tmp/somepath
    nodeFilters:
      - all
ports:
  - port: 8080:80 # http via localhost:8080
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:8443:443 # https via localhost:8443
    nodeFilters:
      - loadbalancer
env:
  - envVar: bar=baz
    nodeFilters:
      - all
labels:
  - label: foo=bar
    nodeFilters:
      - server[0]
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "360s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraServerArgs:
      - --tls-san=127.0.0.1
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true