apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: mysql-secret
    envs:
      - mysql-secret.properties

generatorOptions:
  disableNameSuffixHash: true
  labels:
    generated: "true"

resources:
- deployment.yml
- service.yml