apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeTemplates: true
  pairs:
    version: kcli


namePrefix: kcli
namespace: kcli

patchesJson6902:
- path: patches/patch-limits-2.yml
  target:
    group: apps
    kind: Deployment
    name: mysql
    version: v1


resources:
- mysql
- ../base
- namespace.yml
