apiVersion: apps/v1
kind: Deployment
metadata:
  name: ogum-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ogum
  template:
    metadata:
      labels:
        app: ogum
    spec:
      containers:
      - name: ogum
        image: hashicorp/http-echo:0.2.3
        args:
        - "<body style='background-color:#FF0000;'><h1 style='color:#000080;'>ogum</h1><p>Simple ogum page</p></body>"
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
