kind: Pod
apiVersion: v1
metadata:
  name: foo
  labels:
    app: foo
spec:
  containers:
  - name: foo
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=<h1>foo NAO EH bar</h1>"
    ports:
    - containerPort: 5678
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30950
    port: 5678
  selector:
    app: foo
---
kind: Pod
apiVersion: v1
metadata:
  name: bar
  labels:
    app: bar
spec:
  containers:
  - name: bar
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=<h1>bar NAO EH nem proximo de foo</h1>"
    ports:
    - containerPort: 5678
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bar
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30951
    port: 5678
  selector:
    app: bar
---
