kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: portmapp

nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30950
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP
  - containerPort: 30951
    hostPort: 8081
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
- role: worker
