apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod5984
  labels:
    app: pod5984
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod5984
  template:
    metadata:
      labels:
        app: pod5984
    spec:
      containers:
      - name: pod5984
        image: nginxdemos/hello
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "125Mi"
            cpu: "125m"
          requests:
            memory: "100Mi"
            cpu: "100m"
