apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pg2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg2
  template:
    metadata:
      labels:
        app: pg2
    spec:
      containers:
      - name: postgresql
        image: postgres:14
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
        volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: my-pvc
