---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repset-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rsnginx
  template:
    metadata:
      labels:
        app: rsnginx
    spec:
      containers:
      - name: rsnginx
        image: nginx
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
