version: "3.3"

services:

  traefik:
    image: "s390x/traefik:v3.2"
    container_name: "traefik"
    command:
    healthcheck:
      test: 
        - CMD
        - traefik
        - healthcheck
        - --ping
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8081:80"
      - "8443:443"
      - "8080:8080"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./.certs/:/certs/"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic.yaml:/etc/traefik/dynamic.yaml"

  whoami:
    image: "s390x/nginx:1.26"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.0a0f2746.nip.io`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: 500m
          memory: 1G
        reservations:
          cpus: 125m
          memory: 256M
    depends_on:
      traefik:
        condition: service_healthy
