kind: Deployment
apiVersion: apps/v1
metadata:
  name: tiny1
  namespace: ${APP_NAMESPACE}
  labels:
    app: tiny1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tiny1
  template:
    metadata:
      labels:
        app: tiny1
    spec:
      containers:
        - name: tiny1
          image: tarsoqueiroz/tinywebinfo:1.0
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
            requests:
              cpu: "125m"
              memory: "32Mi"
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tiny1
  namespace: ${APP_NAMESPACE}
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: tiny1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiny1-ingress
  namespace: ${APP_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web9090
spec:
  rules:
    - host: tiny1.0a0f122c.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tiny1
                port: 
                  name: web9090
