apiVersion: v1
kind: Namespace
metadata:
  name: ${APP_NAMESPACE}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: twi1
  namespace: ${APP_NAMESPACE}
  labels:
    app: twi1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twi1
  template:
    metadata:
      labels:
        app: twi1
    spec:
      containers:
        - name: twi1
          image: tarsoqueiroz/tinywebinfo:1.0
          resources:
            limits:
              cpu: "500m"
              memory: "64Mi"
            requests:
              cpu: "250m"
              memory: "32Mi"
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: twi1
  namespace: ${APP_NAMESPACE}
spec:
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    app: twi1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingresshigh
  namespace: ${APP_NAMESPACE}
  annotations:
    # kubernetes.io/ingress.class: traefik
    kubernetes.io/ingress.ingressClassName: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: twi1.0a0f122c.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: twi1
                port:
                  name: web
