apiVersion: v1
kind: ServiceAccount
metadata:
  name: 7-02-tekton-triggers-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 7-02-triggers-eventlistener-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: 7-02-tekton-triggers-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 7-02-triggers-eventlistener-clusterbinding
subjects:
  - kind: ServiceAccount
    name: 7-02-tekton-triggers-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles