apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: .*deployment.*
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DISABLE_STATS
          value: "1"

      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DISABLE_TRACING
          value: "1"

      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: 
          name: DISABLE_PROFILER
          value: "1"
      
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DISABLE_DEBUGGER
          value: "1"
