apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nana-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webapp-service
            port:
              number: 3000
