apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: theingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc0080
            port:
              number: 80
  - http:
      paths:
      - path: /secure
        pathType: Prefix
        backend:
          service:
            name: svc0443
            port:
              number: 443
  - http:
      paths:
      - path: /threethousand
        pathType: Prefix
        backend:
          service:
            name: svc3000
            port:
              number: 3000
