---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  labels:
    name: toolbox
  annotations:
    description: This is a simple pod for use inside of Kubernetes cluster
spec:
  containers:
  - name: toolbox
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo c1; sleep 5 ; done"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "125m"
