apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: 5-09-task
  namespace: default
spec:
  params:
    - name: firstname
      type: string
    - name: lastname
      type: string
  steps:
    - name: echo-fields
      image: ubuntu
      script: |
        #!/bin/bash
        echo "$(params.firstname) $(params.lastname)"
