kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: kind-lab

nodes:
# Control Plane
- role: control-plane
  image: kindest/node:v1.33.1
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "cpu=1000m,memory=1024Mi"

# Worker 1
- role: worker
  image: kindest/node:v1.33.1
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "cpu=2000m,memory=4096Mi"

# Worker 2
- role: worker
  image: kindest/node:v1.33.1
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "cpu=2000m,memory=4096Mi"

# Worker 3
- role: worker
  image: kindest/node:v1.33.1
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "cpu=2000m,memory=4096Mi"

networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
