---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

ports:
  traefik:
    expose: true
    port: 9000
    nodePort: 32090
  web:
    port: 8080
    nodePort: 32080
  websecure:
    port: 8443
    nodePort: 32443
  metrics:
    expose: true
    port: 9100
    nodePort: 32091

service:
  type: NodePort
