apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    version: v1
  name: v1-wordpress
spec:
  ports:
  - nodePort: 30001
    port: 80
  selector:
    app: wordpress
    version: v1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
    version: v1
  name: v1-wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        version: v1
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      volumes:
      - emptyDir: {}
        name: wordpress-persistent-storage
