kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: tmaurice2

nodes:
- role: control-plane
  image: kindest/node:v1.23.6
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-controller=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 6969
    hostPort: 6969
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  - containerPort: 8200
    hostPort: 8200
    protocol: TCP
  - containerPort: 8201
    hostPort: 8201
    protocol: TCP
  - containerPort: 8300
    hostPort: 8300
    protocol: TCP
  - containerPort: 8301
    hostPort: 8301
    protocol: TCP
  - containerPort: 8302
    hostPort: 8302
    protocol: TCP
  - containerPort: 8500
    hostPort: 8500
    protocol: TCP
  - containerPort: 8600
    hostPort: 8600
    protocol: TCP
  - containerPort: 8600
    hostPort: 8600
    protocol: UDP
- role: worker
  image: kindest/node:v1.23.6
- role: worker
  image: kindest/node:v1.23.6
- role: worker
  image: kindest/node:v1.23.6
