apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  # replicas: 3
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  # strategy: {}
  strategy:
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 2
    # type: RollingUpdate
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        # image: nginx
        # image: nginx:1.16.0
        image: nginx:1.15.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.4"
          requests:
            memory: "64Mi"
            cpu: "0.2"
