apiVersion: v1
kind: Pod
metadata:
  name: giropops
spec:
  containers:
  - name: girus
    image: ubuntu
    args:
    - sleep
    - infinity
    volumeMounts:
      - name:  primeiro-emptydir
        mountPath:  /giropops
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name:  primeiro-emptydir
      emptyDir:
        sizeLimit: 256Mi
