apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: meu-nginx
  name: meu-nginx
spec:
  containers:
  - image: nginx
    name: meu-nginx
    resources:
      limits:
        memory: "64Mi"
        cpu: "125m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
