apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  # replicas: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        # image: nginx
        image: nginx:1.19.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "400m"
          requests:
            memory: "64Mi"
            cpu: "200m"
