apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-app
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        # image: nginx:1.19.2
        image: nginx:1.19.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "400m"
          requests:
            memory: "64Mi"
            cpu: "200m"
