apiVersion: v1
kind: Pod
metadata:
  name: giropops
  labels:
    name: giropops
spec:
  containers:
  - name: girus
    image: ubuntu
    args:
    - sleep
    - infinity
    volumeMounts:
      - name: primeiro-emptydir
        mountPath: /giropops
    resources:
      limits:
        memory: "128Mi"
        cpu: "400m"
      requests:
        memory: "64Mi"
        cpu: "200m"
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
