apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["deployments", "services", "configmaps", "secrets", "ingresses", "pods"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
