apiVersion: v1
kind: Pod
metadata:
  name: pod-service-account
  namespace: default
spec:
  serviceAccountName: service-account-example
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["sleep","infinity"]
    resources:
      limits:
        cpu: "1"
        memory: "500M"
      requests:
        cpu: ".5"
        memory: "250M"
