## STATIC CONFIG (restart traefik to update)

# shows you a log msg if a newer image tag can be used
global:
  checkNewVersion: true

# log level: TRACE, DEBUG, INFO, WARN, ERROR (default), FATAL, and PANIC
log:
  level: WARN

# enable dashboard on 8080 with auth
api:
  # Without `auth` uncomment next
  # insecure: true
  # Show dashboard?
  dashboard: true

# enable ping so the `traefik healthcheck` works
ping: {}

# auto-proxy containers if they have proper labels
# and also use this file for dynamic config (tls)
providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

# listen on 80, 443 and 8080
entryPoints:
  web:
    address: :80
    http:
      # redirect all 80 to 443 by 301 status code
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
  traefik:
    address: :8080
