apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: lec-24-
namespace: lec-24

resources:
- ../base
- namespace.yml


components:
  - ../components/mysql
  - ../components/wordpress-dbconfig
  - ../components/mysql-labels
  - ../components/common-annotations

replacements:
- source: 
    name: mysql
    kind: Service
    version: v1
    fieldPath: metadata.name
  targets:
  - select: 
      kind: Deployment
      name: wordpress
    fieldPaths:
    - spec.template.spec.containers.[name=wordpress].env.[name=WORDPRESS_DB_HOST].value