apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: lec-23-


# commonAnnotations:
#   annotated-by: kustomize

# labels:
#   - pairs:
#       mysql: 'true'
#     includeTemplates: true

components:
  - ../components/common-annotations
  - ../components/mysql
  - ../components/mysql-labels


resources:
- ../base
# - mysql