apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: mysql-secret
    envs:
      - mysql-secret.properties

generatorOptions:
  disableNameSuffixHash: true
  labels:
    generated: "true"

commonAnnotations:
  annotated-by: kustomize

resources:
- deployment.yml
- service.yml