- op: replace
  path: /spec/template/spec/containers/0/env
  value:
    - name: WORDPRESS_DB_HOST
      value: mysql
    - name: WORDPRESS_DB_NAME
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_DATABASE
    - name: WORDPRESS_DB_USER
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_USER
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: MYSQL_PASSWORD