apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    version: lec-19
  includeTemplates: true


namePrefix: lec-19-
namespace: lec-19

patchesJson6902:
  - path: patches/patch-limits-2.yml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: mysql


resources:
- mysql
- ../base
- namespace.yml