apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["sh", "-c", "echo Hello > /data/hello.txt; sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: temp-storage
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: temp-storage
    emptyDir: {}
