apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: app-container-hostpath
    image: busybox
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "250m"
        memory: "128Mi"
    command: ["sh", "-c", "hostname >> /host-data/nameofhost.txt ; date >> /host-data/nameofhost.txt ; ls /host-data ; sleep 3600"]
    volumeMounts:
    - mountPath: /host-data
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /data
      type: Directory
