apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["sh", "-c", "cat /secrets/imperative/app-secret-imperative ; cat /secrets/declarative/app-secret-declarative ; sleep 3600"]
    volumeMounts:
    - mountPath: /secrets/imperative
      name: secret-volume-imperative
    - mountPath: /secrets/declarative
      name: secret-volume-declarative
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: secret-volume-imperative
    secret:
      secretName: app-secret-imperative
  - name: secret-volume-declarative
    secret:
      secretName: app-secret-declarative
