apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  version: lec-15

namePrefix: lec-15-

namespace: lec-15

# transformers:
#   - ./transformers/namespace.yml

resources:
- mysql
- ../base
- namespace.yml 