# This rule is not used by the project pod-diagnoser-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the diagnostics.7f000001.nip.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-diagnoser-operator
    app.kubernetes.io/managed-by: kustomize
  name: poddiagnoser-editor-role
rules:
- apiGroups:
  - diagnostics.7f000001.nip.io
  resources:
  - poddiagnosers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - diagnostics.7f000001.nip.io
  resources:
  - poddiagnosers/status
  verbs:
  - get
