# This rule is not used by the project pod-diagnoser-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over diagnostics.7f000001.nip.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-diagnoser-operator
    app.kubernetes.io/managed-by: kustomize
  name: poddiagnoser-admin-role
rules:
- apiGroups:
  - diagnostics.7f000001.nip.io
  resources:
  - poddiagnosers
  verbs:
  - '*'
- apiGroups:
  - diagnostics.7f000001.nip.io
  resources:
  - poddiagnosers/status
  verbs:
  - get
