kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio
nodes:
  - role: control-plane
    # kubeadmConfigPatches:
    #   - |
    #     kind: InitConfiguration
    #     nodeRegistration:
    #       kubeletExtraArgs:
    #         node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30008
        hostPort: 80
        protocol: TCP
      - containerPort: 30344
        hostPort: 443
        protocol: TCP
      # - containerPort: 30808
      #   hostPort: 8080
      #   protocol: TCP
      # - containerPort: 30348
      #   hostPort: 8443
      #   protocol: TCP
      # - containerPort: 30909
      #   hostPort: 9090
      #   protocol: TCP
  - role: worker
  - role: worker
  - role: worker
networking:
  # disableDefaultCNI: true
  apiServerPort: 6443
  apiServerAddress: "0.0.0.0"
