apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx8080
  namespace: default
  labels:
    app: nginx8080
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx8080
  template:
    metadata:
      labels:
        app: nginx8080
    spec:
      containers:
        - name: nginx8080
          image: gcr.io/google-samples/hello-app:2.0 # n ginxdemos/hello:80 | gcr.io/google-samples/hello-app:{1|2}.0:8080
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: "125Mi"
              cpu: "125m"
            requests:
              memory: "100Mi"
              cpu: "100m"
