apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  ports:
    - name: 80-80
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: nginx
  type: ClusterIP
  sessionAffinity: None
