apiVersion: v1
data:
  MYSQL_DATABASE: d29yZHByZXNz
  MYSQL_ROOT_PASSWORD: YWRtaW4=
kind: Secret
metadata:
  labels:
    generated: "true"
    version: v113
  name: v113-mysql-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    version: v113
  name: v113-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    version: v113
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    version: v113
  name: v113-wordpress
spec:
  ports:
  - nodePort: 30001
    port: 80
  selector:
    app: wordpress
    version: v113
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    version: v113
  name: v113-mysql
spec:
  selector:
    matchLabels:
      app: mysql
      version: v113
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        version: v113
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: v113-mysql-secret
        image: mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      volumes:
      - emptyDir: {}
        name: mysql-persistent-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
    version: v113
  name: v113-wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      version: v113
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        version: v113
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      volumes:
      - emptyDir: {}
        name: wordpress-persistent-storage
