apiVersion: k3d.io/v1alpha2
kind: Simple
name: tqK3d
servers: 3
agents: 0
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443" # Kubernetes API via localhost:6443
image: rancher/k3s:v1.22.2-k3s2
volumes:
  - volume: /tmp:/Data/Learn/aboutContainers/K3d/tqBasic/tmp
    nodeFilters:
      - all
ports:
  - port: 8880:80 # http via localhost:8880
    nodeFilters:
      - loadbalancer
  - port: 8843:443 # https via localhost:8843
    nodeFilters:
      - loadbalancer
  - port: 8080:8080 # http via localhost:8080
    nodeFilters:
      - loadbalancer
  - port: 8043:8443 # https via localhost:8443
    nodeFilters:
      - loadbalancer
env:
  - envVar: bar=tolomeu
    nodeFilters:
      - all
labels:
  - label: foo=bregas
    nodeFilters:
      - server[0]
      - loadbalancer

options:
  k3d:
    wait: true
    timeout: "360s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraServerArgs:
      - --tls-san=127.0.0.1
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true