apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    version: v1
  name: v1-convenience-wordpress-transformers
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
    version: v1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
    version: v1
  name: v1-convenience-wordpress-transformers
spec:
  selector:
    matchLabels:
      app: wordpress
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        version: v1
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
      volumes:
      - emptyDir: {}
        name: wordpress-persistent-storage
