kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: ingressbasic

nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        service-node-port-range: "80,443,153"
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
    listenAddress: "0.0.0.0" 
  - containerPort: 443
    hostPort: 443
    protocol: TCP
    listenAddress: "0.0.0.0" 
  - containerPort: 153
    hostPort: 153
    protocol: TCP
    listenAddress: "0.0.0.0" 
  - containerPort: 153
    hostPort: 153
    protocol: UDP
    listenAddress: "0.0.0.0" 
- role: worker
- role: worker
- role: worker
