---
# Kind configuration file
#
# Nodes         : 1x control plane
#                 3x workers
# K8s version   : 1.28 (from https://github.com/kubernetes-sigs/kind/releases)
# Ingress       : enabled
# Port Mappings
#   TCP         : 80,443
# 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: storage

networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"

# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta3
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname

# 1 control plane node and 3 workers
nodes:
- role: control-plane
  image: kindest/node:v1.28.7@sha256:9bc6c451a289cf96ad0bbaf33d416901de6fd632415b076ab05f5fa7e4f65c58
  extraMounts:
  - hostPath: ./vol.data/controlplane
    containerPath: /Data
    readOnly: false # default false
    selinuxRelabel: false # default false
    propagation: None # optional: set propagation mode (None, HostToContainer or Bidirectional)
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-controller=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

- role: worker
  image: kindest/node:v1.28.7@sha256:9bc6c451a289cf96ad0bbaf33d416901de6fd632415b076ab05f5fa7e4f65c58
  extraMounts:
  - hostPath: ./vol.data/worker0
    containerPath: /Data
    readOnly: false # default false
    selinuxRelabel: false # default false
    propagation: None # optional: set propagation mode (None, HostToContainer or Bidirectional)

- role: worker
  image: kindest/node:v1.28.7@sha256:9bc6c451a289cf96ad0bbaf33d416901de6fd632415b076ab05f5fa7e4f65c58
  extraMounts:
  - hostPath: ./vol.data/worker1
    containerPath: /Data
    readOnly: false # default false
    selinuxRelabel: false # default false
    propagation: None # optional: set propagation mode (None, HostToContainer or Bidirectional)

- role: worker
  image: kindest/node:v1.28.7@sha256:9bc6c451a289cf96ad0bbaf33d416901de6fd632415b076ab05f5fa7e4f65c58
  extraMounts:
  - hostPath: ./vol.data/worker2
    containerPath: /Data
    readOnly: false # default false
    selinuxRelabel: false # default false
    propagation: None # optional: set propagation mode (None, HostToContainer or Bidirectional)
