kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: extramount

nodes:
- role: control-plane
  extraMounts:
  - hostPath: ./vol.data/extramount.controlplane
    containerPath: /Data
    readOnly: false # default false
    selinuxRelabel: false # default false
    propagation: None # optional: set propagation mode (None, HostToContainer or Bidirectional)
- role: worker
- role: worker
  extraMounts:
  - hostPath: ./vol.data/extramount.worker2
    containerPath: /Data
