kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: c1
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: 10.240.0.0/16
  serviceSubnet: 10.110.0.0/16
  apiServerPort: 6443
