kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: c1
nodes:
- role: control-plane
- role: worker
networking:
  disableDefaultCNI: true
  apiServerAddress: 10.15.18.44 # PUT YOUR IP ADDRESSS OF YOUR MACHINE HERE!
  apiServerPort: 6441
  podSubnet: "10.0.0.0/16"
  serviceSubnet: "10.1.0.0/16"
