kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: c2
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: 10.241.0.0/16
  serviceSubnet: 10.111.0.0/16
  apiServerPort: 6444
