apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: helm-

resources:
# - mysql
# - ../base
- namespace.yml

# Install mysql using helm chart
helmCharts:
  - name: mysql
    # version: 9.4.0
    # repo:  https://charts.bitnami.com/bitnami
    releaseName: mysql-demo
    namespace: database
    # chartHome: mysql - local chart
    # configHome: mysql - default ({tmpDir}/helm)
    # valuesFile: mysql/values.yaml
    # valuesInline:
    # includeCRDs: true
  - name: prometheus
    # repo: https://prometheus-community.github.io/helm-charts
    # version: 14.3.0
    releaseName: prometheus-demo
    namespace: monitoring
    

helmGlobals:
  chartHome: charts-store


# https://github.com/kubernetes-sigs/kustomize/issues/4401